# Generated by Django 3.0.7 on 2020-06-28 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='nextNode',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='article',
            name='prevNode',
            field=models.SlugField(blank=True),
        ),
    ]
