# Generated by Django 3.0.7 on 2020-06-28 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20200628_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='nextNodeTitle',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='article',
            name='prevNodeTitle',
            field=models.TextField(blank=True),
        ),
    ]
