# Generated by Django 3.0.7 on 2020-06-28 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20200628_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='nextNodeTitle',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='prevNodeTitle',
            field=models.CharField(max_length=100),
        ),
    ]
