# Generated by Django 3.0.7 on 2020-06-28 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20200628_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tagString',
            field=models.CharField(default='', max_length=100),
        ),
    ]
