# Generated by Django 3.0.7 on 2020-06-28 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_article_tagstring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='nextNodeTitle',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='article',
            name='prevNodeTitle',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
