# Generated by Django 3.0.7 on 2020-07-05 04:19

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_auto_20200705_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='nextNodeTitle',
        ),
        migrations.RemoveField(
            model_name='article',
            name='prevNodeTitle',
        ),
        migrations.AddField(
            model_name='article',
            name='body_ko',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='article',
            name='description_ko',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_ko',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.TextField(default=''),
        ),
    ]
