# Generated by Django 3.0.7 on 2020-07-05 05:07

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_auto_20200705_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='description_ko',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Content_ko'),
        ),
    ]
